### ISSUE TITLE
[Bug] Just a question .. (Not a bug)

### ISSUE THREAD

**Issue by jeffkershner** [creativetimofficial/ct-soft-ui-dashboard-pro-material-ui#1]
### Version
1.0
### Reproduction link
http://localhost
### Operating System
MAC
### Device
n/a
### Browser & Version
n/a
### Steps to reproduce
I have followed the quick start: https://www.creative-tim.com/learning-lab/material-ui/quick-start/soft-ui-dashboard
... and I have the dashboard up and running locally.

I have just a question... Since this is a template showcasing lots of different UI elements, do you think it would be better when creating a new project to:
1. Start with a blank react-app project and import things from the template as needed or
2. Start with the large template and remove unused features/pages/components?
### What is expected?
n/a
### What is actually happening?
n/a

---

**Comment by sajadevo** [comment]
**Hi @jeffkershner**
Thanks for using our product, as the product is not a npm package you can go ahead with the second option: 
Start with the large template and remove unused features/pages/components

**All the best**
**Sajad**
